---

- name: Install pip (not Archlinux)
  when: ansible_distribution != 'Archlinux'
  package:
    name: '{{ pip_package_name[ansible_os_family] }}'
    state: present

- name: Install pip (Archlinux)
  when: ansible_distribution == 'Archlinux'
  shell: pacman -Sy --noconfirm python-pip

- name: Pip install setuptools
  when: ansible_distribution != 'Archlinux'
  pip:
    name: setuptools
    state: latest
    executable: pip3

- name: Pip install your package
  pip:
    name: '{{ name }}'
    state: latest
    executable: pip3
