---

- name: Install pip
  package:
    name: '{{ pip_package_name[ansible_os_family] }}'
    state: present

- name: Pip install setuptools
  pip:
    name: setuptools
    state: latest
    executable: pip3

- name: Find if pip3 exists
  shell: which pip3
  failed_when: false
  register: pip3

- name: Pip install your package
  pip:
    name: '{{ name }}'
    state: latest
    executable: '{{ "pip3" if pip3.rc == 0 else "pip" }}'
